<?php

return $GLOBALS["_ABBR"] = json_decode(
'{"ante":"a","abbreviation":"abbrev","aberdeen":"abd","aberdeenshire":
"aberdeensh","ablative":"abl","abolition":"abol","aboriginal":
"aborig","archbishop":"abp","abridged":"abr","abridgement":"abridgem"
,"absolute":"absol","abstract":"abst","academia":"acad","academy":
"acad","academic":"acad","according":"acc","accusative":"acc",
"account":"acc","acceptance":"accept","accommodation":"accomm",
"accomplished":"accompl","accounts":"accs","achievement":"achievem",
"annodomini":"ad","adaptationof":"ad","addendum":"add","addenda":
"add","addition":"addit","address":"addr","adjective":"adj",
"adjectival":"adj","adjectivalphrase":"adjphr","adjectives":"adjs",
"admiral":"adm","admiralty":"adm","administration":"admin",
"administrative":"admin","admonition":"admon","adverb":"adv",
"adverbial":"adv","advanced":"adv","advances":"adv","adventure":"adv"
,"advices":"adv","advocate":"adv","advancement":"advancem",
"advertisement":"advert","adverbs":"advs","advertisements":"advts",
"aerodynamics":"aerodynam","aeronautics":"aeronaut","aeronautical":
"aeronaut","affairs":"aff","affecting":"affect","affection":"affect",
"africa":"afr","agriculture":"agric","agricultural":"agric","against"
:"agst","alchemy":"alch","algebra":"alg","allegiance":"alleg",
"alliterative":"allit","almanac":"alm","alphabet":"alph",
"alphabetical":"alph","alteration":"alt","america":"amer","american":
"amer","analysis":"anal","analytic":"analyt","anatomy":"anat",
"avenue":"ave","hs":"high","grade":"","preparatory":"prep",
"anatomical":"anat","ancient":"anc","anecdotes":"anecd","anglian":
"ang","angloindian":"angloind","animal":"anim","annal":"ann","annual"
:"ann","anniversary":"anniv","annotation":"annot","anonymous":"anon",
"answer":"answ","antiquities":"ant","anthropology":"anthrop",
"anthropological":"anthropol","antiquity":"antiq","aphetic":"aphet",
"aphetized":"aphet","apocalyptic":"apoc","apology":"apol","apologies"
:"apol","apparently":"app","appendix":"app","applied":"appl",
"application":"applic","appositive":"appos","april":"apr","arabic":
"arab","arber":"arb","archaic":"arch","architecture":"arch","archive"
:"arch","archaeology":"archaeol","archaeological":"archaeol",
"archipelago":"archipel","architectural":"archit","argument":"argt",
"arithmetic":"arith","arithmetical":"arithm","arrangement":"arrangem"
,"article":"art","articulation":"artic","artificial":"artific",
"artillery":"artill","ashmole":"ashm","assembly":"assemb",
"assemblies":"assemb","association":"assoc","associationfootball":
"assocfootball","assyriology":"assyriol","astronomy":"astr",
"astrology":"astrol","astronomic":"astron","astronautics":"astronaut"
,"astronautical":"astronaut","attic":"att","attributive":"attrib",
"attribute":"attrib","august":"aug","australia":"austral","author":
"auth","autobiography":"autobiog","autobiographic":"autobiogr",
"authorizedversion":"av","ayrshire":"ayrsh","bacteriology":
"bacteriol","bacteriologic":"bacteriol","beforechrist":"bc",
"britishcolumbia":"bc","bedfordshire":"bedford","before":"bef",
"belandthedragon":"beldr","belgian":"belg","berkshire":"berks",
"berwickshire":"berw","between":"betw","bibliography":"bibliogr",
"biochemistry":"biochem","biochemical":"biochem","biography":"biog",
"biographic":"biogr","biology":"biol","biological":"biol","book":"bk"
,"books":"bks","britishnationalcorpus":"bnc","border":"bord","botany"
:"bot","botanic":"bot","bishop":"bp","brazilian":"braz","britain":
"brit","british":"brit","buckinghamshire":"bucks","building":"build",
"bulletin":"bull","bureau":"bur","century":"c","county":"c",
"counties":"c","circa":"c","calendar":"cal","calculus":"calc",
"california":"calif","calligraphy":"calligr","cambridge":"camb",
"campanology":"campanol","canadian":"canad","canterbury":"canterb",
"captain":"capt","cartography":"cartogr","cartographic":"cartogr",
"catalogue":"catal","catechism":"catech","catholic":"cath","central":
"cent","ceramics":"ceram","certificate":"cert","confer":"cf",
"compare":"cf","church":"ch","chamber":"chamb","character":"char",
"charles":"chas","chemicalengineering":"chemengin","chemistry":"chem"
,"chemical":"chem","cheshire":"chesh","churchhistory":"chhist",
"christian":"chr","chronicles":"chr","chronology":"chron","chronicle"
:"chron","cinematography":"cinematogr","cinematographic":"cinematogr"
,"circle":"circ","civillaw":"civlaw","civilengineering":"civilengin",
"clause":"cl","club":"cl","classicalantiquities":"classantiq",
"classical":"class","classification":"classif","climatology":
"climatol","clinical":"clin","cognatewith":"cognw","colonel":"col",
"colossians":"col","collected":"coll","collection":"coll","college":
"coll","collective":"collect","colloquial":"colloq","colloquies":
"colloq","common":"com","commission":"com","combination":"comb",
"combiningform":"combform","combinations":"combs","commerce":"comm",
"incommercialusage":"comm","commentary":"comm","committee":"comm",
"commandment":"commandm","commendation":"commend","commercial":
"commerc","commerciallaw":"commlaw","commonwealth":"commonw",
"communication":"communic","comparative":"comp","compound":"comp",
"composition":"comp","companion":"comp","company":"comp",
"comparativeanatomy":"companat","compendium":"compend","compendious":
"compend","complement":"compl","complete":"compl","concerning":"conc"
,"concise":"conc","conchology":"conch","conclusion":"concl",
"concrete":"concr","conference":"conf","confession":"conf",
"confidential":"confid","conflict":"confl","confutation":"confut",
"congress":"congr","congregation":"congreg","congressional":
"congress","conjugation":"conj","conjunction":"conj","connecticut":
"conn","consonant":"cons","conscience":"consc","consecrated":
"consecr","consecration":"consecr","consideration":"consid",
"consolation":"consol","construction":"const","construedwith":"const"
,"constitutionalhistory":"constithist","constitution":"constit",
"contemporary":"contemp","contemplation":"contempl","contemptuous":
"contempt","contending":"contend","contention":"content",
"continuation":"contin","contracted":"contr","contraction":"contr",
"contrasted":"contr","contradiction":"contradict","contribution":
"contrib","controversial":"controv","controversy":"controv",
"convention":"conv","conversation":"conversat","convocation":"convoc"
,"corinthians":"cor","cornwall":"cornw","coronation":"coron",
"correspondence":"corr","corresponding":"corresp","council":"counc",
"courtship":"courtsh","craniology":"craniol","craniometry":"craniom",
"criminal":"crim","criminallaw":"crimlaw","critical":"crit",
"criticism":"crit","court":"crt","courts":"crts","cryptography":
"cryptogr","crystallography":"crystallogr","count":"ct","cumberland":
"cumb","cyclopaedia":"cycl","cytology":"cytol","cytological":"cytol",
"daniel":"dan","dative":"dat","daughter":"dau","districtofcolumbia":
"dc","debate":"deb","december":"dec","declaration":"declar",
"dedicated":"ded","dedication":"ded","definite":"def","definition":
"def","defence":"def","deliverance":"deliv","demonstrative":"dem",
"demonstration":"demonstr","department":"dep","deputy":"dep",
"depredation":"depred","derbyshire":"derbysh","derivative":"deriv",
"derogatory":"derog","description":"descr","descriptive":"descr",
"deuteronomy":"deut","development":"devel","devonshire":"devonsh",
"dialect":"dial","dictionary":"dict","difficult":"diffic",
"difficulty":"diffic","diminutive":"dim","direction":"direct",
"disease":"dis","discourse":"disc","discipline":"discipl","discovery"
:"discov","discrimination":"discrim","discussion":"discuss",
"dissertation":"diss","district":"dist","distemper":"distemp",
"distilling":"distill","distribution":"distrib","divinity":"div",
"division":"div","diversity":"divers","duke":"dk","document":"doc",
"doctrine":"doctr","domestic":"domest","durham":"durh","dyslogistic":
"dyslog","east":"e","eastern":"e","eastafrica":"eafr","eastanglia":
"eangl","eastanglian":"eanglian","eastindies":"eastind","eastindian":
"eastind","ecclesiastical":"eccl","ecclesiastes":"eccl",
"ecclesiasticalhistory":"ecclhist","ecclesiasticallaw":"eccllaw",
"ecclesiasticus":"ecclus","ecology":"ecol","ecological":"ecol",
"economics":"econ","economic":"econ","edition":"ed","edward":"ed",
"englishdialectdictionary":"edd","edinburgh":"edin","education":
"educ","earlyenglishtextsociety":"eets","egyptian":"egypt",
"egyptology":"egyptol","electricity":"electr","electric":"electr",
"electricalengineering":"electrengin","electromagnetism":
"electromagn","electrophysiology":"electrophysiol","element":"elem",
"elementary":"elem","k6":"elem","k7":"elem","k8":"elem",
"elizabeth":"eliz","elizabethan":"elizab",
"elliptical":"ellipt","embassy":"emb","embryology":"embryol",
"embryologic":"embryol","eastmidland":"emidl","emphatic":"emph",
"encyclopaedia":"encycl","encyclopaedic":"encycl",
"encyclopaediabritannica":"encyclbrit","encyclopaediametropolitana":
"encyclmetrop","england":"eng","english":"eng","engineering":"engin",
"englishwomen":"englishw","enquiry":"enq","entomology":"ent",
"entomological":"ent","enthusiasm":"enthus","enzymology":"enzymol",
"earlyoldenglish":"eoe","epistle":"ep","ephesians":"eph","epilogue":
"epil","episcopacy":"episc","epitaph":"epit","equipment":"equip",
"erroneous":"erron","esdras":"esd","especially":"esp","essay":"ess",
"essential":"essent","establishment":"establ","esther":"esth",
"ethnology":"ethnol","etymology":"etym","etymological":"etymol",
"euphemistic":"euphem","evaluation":"eval","evangelical":"evang",
"evening":"even","evidence":"evid","evolution":"evol","evolutionary":
"evol","executivedocument":"exdoc","exaltation":"exalt","examination"
:"exam","except":"exc","exchange":"exch","exchequer":"exch",
"execution":"exec","executive":"exec","exercise":"exerc","exhibition"
:"exhib","exhibit":"exhib","exodus":"exod","expedition":"exped",
"experiment":"exper","experimental":"exper","explanation":"explan",
"explication":"explic","exploration":"explor","exposition":"expos",
"expository":"expos","ezekiel":"ezek","feminine":"f","folio":"f",
"fable":"fab","familiar":"fam","family":"fam","farewell":"farew",
"february":"feb","folios":"ff","fifeshire":"fifesh","figurative":
"fig","floruit":"fl","flourished":"fl","footprint":"footpr",
"forfarshire":"forfarsh","fortification":"fortif","fortnightly":
"fortn","foundation":"found","father":"fr","french":"fr","from":"fr",
"fragment":"fragm","fraternity":"fratern","frequently":"freq",
"friendship":"friendsh","fundamental":"fund","furniture":"furnit",
"future":"fut","galatians":"gal","garden":"gard","gardening":"gard",
"gastronomy":"gastron","gazette":"gaz","good":"gd","general":"gen",
"genitive":"gen","genesis":"gen","george":"geo","geography":"geog",
"geographic":"geogr","geology":"geol","geologic":"geol","geometry":
"geom","geometric":"geom","geomorphology":"geomorphol","german":"ger"
,"gerundial":"gerund","glacier":"glac","glasgow":"glasg",
"gloucestershire":"glos","glossary":"gloss","gospel":"gosp",
"government":"gov","grammar":"gr","grammaticalanalysis":
"grammanalysis","great":"gt","gynaecology":"gynaecol","habakkuk":
"hab","haematology":"haematol","haggai":"hag","hampshire":"hampsh",
"handbook":"handbk","hebrew":"heb","hebrews":"heb","henry":"hen",
"heraldry":"her","herbalism":"herb","herefordshire":"heref",
"hertfordshire":"hertfordsh","hieroglyphic":"hierogl","historical":
"hist","history":"hist","historic":"hist","histology":"histol",
"histologic":"histol","homilies":"hom","horology":"horol",
"horticulture":"hort","horticultural":"hort","hosea":"hos","hospital"
:"hosp","household":"househ","housekeeping":"housek","husbandry":
"husb","hydraulic":"hydraul","hydrology":"hydrol","hydrological":
"hydrol","ichthyology":"ichth","icthyology":"icthyol","ideology":
"ideol","ideological":"ideol","idolatry":"idol","illustrated":
"illustr","illustration":"illustr","imaginary":"imag","imagination":
"imag","imitative":"imit","immunology":"immunol","imperative":"imp",
"imperfect":"imperf","impersonal":"impers","impression":"impr",
"imprint":"impr","improved":"impr","improper":"improp","inaugural":
"inaug","inclosure":"inclos","india":"ind","indicative":"ind",
"indirect":"ind","industry":"ind","indefinite":"indef","industrial":
"industr","industrialrelations":"industrrel","infinitive":"infin",
"influenced":"infl","influence":"infl","innocence":"innoc","innocent"
:"innoc","inorganic":"inorg","inquiry":"inq","institute":"inst",
"institution":"inst","instrumental":"instr","instruction":"instr",
"interjection":"int","intelligence":"intell","intelligent":"intell",
"intellectual":"intellect","intercourse":"interc","interlude":
"interl","international":"internat","interpretation":"interpr",
"interrogative":"interrog","intransitive":"intr","introduction":
"intro","introductory":"introd","inventory":"inv","inventories":"inv"
,"invention":"invent","invertebrate":"invertebr","invertebrated":
"invertebr","invertebratezoology":"invertzool","investigation":
"investig","investment":"investm","invocation":"invoc","irish":"ir",
"ireland":"irel","ironically":"iron","irregular":"irreg","isaiah":
"isa","italian":"ital","jahrbuch":"jahrb","james":"jam","jamieson":
"jam","january":"jan","japanese":"jap","jeremiah":"jer","jocular":
"joc","joshua":"josh","journal":"jrnl","journals":"jrnls","judges":
"jud","july":"jul","june":"jun","junior":"jun","jurisdiction":
"jurisd","jurisprudence":"jurispr","justification":"justif","king":
"k","kentish":"kent","kings":"kgs","kingsbenchdivision":
"kingsbenchdiv","kingdom":"kingd","knowledge":"knowl","keeper":"kpr",
"line":"l","laboratory":"lab","lamentations":"lam","lamentation":
"lament","lancashire":"lanc","language":"lang","languages":"langs",
"latin":"lat","lord":"ld","lords":"lds","lecture":"lect","leechdom":
"leechd","legend":"leg","leicestershire":"leicest","letter":"let",
"letters":"lett","leviticus":"lev","lexicon":"lex","library":"libr",
"limnology":"limnol","lincolnshire":"lincolnsh","linguistic":"ling",
"linnean":"linn","literal":"lit","literary":"lit","literature":"lit",
"lithography":"lithogr","lithology":"lithol","liturgy":"liturg",
"lines":"ll","lateoldenglish":"loe","london":"lond","septuagint":
"lxx","masculine":"m","maccabees":"macc","machinery":"mach","machine"
:"mach","magazine":"mag","magnetism":"magn","magnetic":"magn",
"malachi":"mal","manual":"man","management":"managem","manchester":
"manch","manipulation":"manip","manufacturing":"manuf","manufacture":
"manuf","march":"mar","massachussets":"mass","mathematics":"math",
"mathematical":"math","matthew":"matt","measure":"meas","measurement"
:"measurem","mechanics":"mech","mechanical":"mech","medieval":"med",
"medicine":"med","medical":"med","meditation":"medit","memoir":"mem",
"mercury":"merc","merchant":"merch","metallurgy":"metall",
"metalliferous":"metallif","metallography":"metallogr",
"metallographic":"metallogr","metamorphosis":"metamorph",
"metaphysics":"metaph","metaphorical":"metaphor","meteorology":
"meteorol","meteorologic":"meteorol","method":"meth","metrigratia":
"metrgr","metropolitan":"metrop","metropolis":"metrop","mexican":
"mex","micah":"mic","michigan":"mich","microbiology":"microbiol",
"microscopic":"microsc","midland":"midl","military":"mil",
"mineralogy":"min","minaralogic":"mineral","miscellaneous":"misc",
"miscellany":"misc","misprinted":"mispr","modern":"mod","monument":
"monum","morphology":"morphol","manuscript":"ms","manuscripts":"mss",
"mount":"mt","meeting":"mtg","mountains":"mts","municipal":"munic",
"munificence":"munif","muniment":"munim","music":"mus","musical":
"mus","museum":"mus","mystery":"myst","mythology":"myth","neuter":"n"
,"north":"n","noun":"n","northern":"n","northafrica":"nafr","nahum":
"nah","northamerica":"namer","narrative":"narr","natural":"nat",
"naturalhistory":"nathist","naturalphilosophy":"natphilos",
"naturalscience":"natsci","nautical":"naut","naval":"nav",
"navigation":"nav","northcarolina":"ncarolina","northdakota":
"ndakota","northeastern":"ne","northeast":"ne","newenglishdictionary"
:"ned","nehemiah":"neh","neighbour":"neighb","neighbourhood":"neighb"
,"nervous":"nerv","neurology":"neurol","neurologic":"neurol",
"neurosurgery":"neurosurg","newhampshire":"newhampsh","newcastle":
"newc","newsprint":"newspr","northernirish":"nir","northernireland":
"nirel","number":"no","nominative":"nom","nonconformist":"nonconf",
"nonceword":"noncewd","norfolk":"norf","northamptonshire":
"northamptonsh","northumberland":"northumb","northumbrian":"northumb"
,"norwegian":"norw","nottinghamshire":"notts","november":"nov",
"nouns":"ns","newsouthwales":"nswales","newtestament":"nt","nuclear":
"nucl","numbers":"num","numismatics":"numism","northwestern":"nw",
"northwest":"nw","newyork":"ny","newzealand":"nz","obadiah":"obad",
"obedience":"obed","object":"obj","objective":"obj","oblique":"obl",
"obsolete":"obs","observation":"observ","obstetric":"obstet",
"obstetricmedicine":"obstetrmed","occasionally":"occas","occasional":
"occas","occupation":"occup","occurrence":"occurr","oceanography":
"oceanogr","oceanographic":"oceanogr","october":"oct","oldenglish":
"oe","oxfordenglishdictionary":"oed","official":"off","office":"off",
"oklahoma":"okla","ontario":"ont","ophthalmology":"ophthalm",
"ophtalmologic":"ophthalmol","opposed":"opp","theopposite":"opp",
"oppression":"oppress","optics":"opt","oracle":"orac","order":"ord",
"ordinance":"ord","organic":"org","organicchemistry":"organchem",
"origin":"orig","original":"orig","orkney":"orkn","ornithology":
"ornith","ornithologic":"ornithol","orthography":"orthogr",
"oldtestament":"ot","outline":"outl","oxford":"oxf","oxfordshire":
"oxfordsh","page":"p","past":"pa","pennsylvania":"pa","palaeobotany":
"palaeobot","palaeography":"palaeogr","palaeontology":"palaeont",
"palaeontologic":"palaeontol","passiveparticiple":"papple",
"pastparticiple":"papple","paraphrase":"paraphr","paraphrased":
"paraphr","parasitology":"parasitol","parliament":"parl",
"parliamentary":"parl","parnassus":"parnass","passive":"pass",
"pasttense":"pat","pathology":"path","pathologic":"path","peculation"
:"peculat","peninsula":"penins","perfect":"perf","perfection":"perf",
"perhaps":"perh","periodontology":"periodontol","periodontologic":
"periodontol","person":"pers","persian":"pers","personal":"pers",
"persecution":"persec","personified":"personif","perthshire":
"perthsh","peter":"pet","petrography":"petrogr","petrographic":
"petrogr","petrology":"petrol","petrologic":"petrol","pharmacology":
"pharm","pharmaceutical":"pharmaceut","pharmacological":"pharmacol",
"philosophy":"phil","philosophic":"phil","philippians":"phil",
"philadelphia":"philad","philemon":"philem","philology":"philol",
"philologic":"philol","phoenician":"phoen","phonetic":"phonet",
"phonology":"phonol","photography":"photog","photographic":"photogr",
"phrase":"phr","phrenology":"phrenol","physiology":"phys",
"physicalchemistry":"physicalchem","physicalgeography":
"physicalgeogr","physiography":"physiogr","physiologic":"physiol",
"pictorial":"pict","picture":"pict","plural":"pl","poetic":"poet",
"poetical":"poet","politics":"pol","political":"pol",
"politicaleconomy":"polecon","polytechnic":"polytechn","popular":
"pop","porcelain":"porc","portuguese":"port","possessive":"poss",
"possible":"poss","possibly":"poss","posthumous":"posth","postmaster"
:"postm","pottery":"pott","participial":"ppl","participialadjective":
"ppla","participialadjectives":"ppladjs","participle":"pple",
"participles":"pples","publicrecords":"pr","present":"pr","practical"
:"pract","practice":"pract","preceding":"prec","predicate":"pred",
"predicative":"predic","prediction":"predict","prefix":"pref",
"preface":"pref","prehistoric":"preh","prehistory":"prehist",
"preposition":"prep","prerogative":"prerog","presbyterian":"presb",
"presbytery":"presb","preservation":"preserv","presentparticiple":
"prespple","primer":"prim","principle":"princ","printing":"print",
"privative":"priv","probably":"prob","probability":"probab",
"probabilities":"probab","problem":"probl","proceedings":"proc",
"product":"prod","prologue":"prol","pronoun":"pron","pronunciation":
"pron","properly":"prop","property":"prop","properties":"prop",
"proprietary":"propr","prosody":"pros","proverb":"prov","proverbs":
"prov","providence":"provid","provincial":"provinc","provisional":
"provis","psalms":"ps","pseudoarchaic":"pseudoarch","pseudodialect":
"pseudodial","pseudoscots":"pseudosc","psychology":"psych",
"psychoanalysis":"psychoanal","psychoanalytic":"psychoanalyt",
"psychologic":"psychol","psychopathology":"psychopathol",
"psychopathologic":"psychopathol","part":"pt","public":"publ",
"publication":"publ","purgatory":"purg","quarterly":"q","queen":"q",
"queenelizabeth":"qeliz","queensland":"qld","quantummechanics":
"quantummech","queensbenchdivision":"queensbenchdiv","quotation":
"quot","quotations":"quots","quodvide":"qv","whichsee":"qv","royal":
"r","radiology":"radiol","royalairforce":"raf","romancatholic":"rc",
"romancatholicchurch":"rcchurch","reason":"reas","rebellion":"reb",
"record":"rec","reclamation":"reclam","recollection":"recoll",
"redemption":"redempt","reduplicating":"redupl","reference":"ref",
"reformation":"ref","refashioned":"refash","refashioning":"refash",
"reflexive":"refl","reflection":"refl","refusal":"refus","refutation"
:"refut","regular":"reg","register":"reg","regicide":"regic",
"related":"rel","relative":"rel","relating":"rel","religion":"relig",
"religious":"relig","reminiscence":"reminisc","remonstrance":
"remonstr","renfrewshire":"renfrewsh","report":"rep","representative"
:"repr","representing":"repr","reproduction":"reprod","reproductive":
"reprod","republic":"repub","research":"res","residence":"resid",
"residential":"resid","return":"ret","retrospective":"retrosp",
"review":"rev","revised":"rev","revelation":"rev","revolution":
"revol","rhetoric":"rhet","rhetorical":"rhet","rhodeisland":
"rhodeisl","richard":"rich","royalnavy":"rn","roman":"rom","romans":
"rom","romanantiquities":"romantiq","rossshire":"rosssh","roxburgh":
"roxb","rudiment":"rudim","russia":"russ","russian":"russ","south":
"s","southern":"s","southafrica":"safr","samuel":"sam","saskatchewan"
:"sask","saturday":"sat","saxon":"sax","scilicet":"sc",
"understandorsupply":"sc","scottish":"sc","scots":"sc","scandinavia":
"scand","scandinavian":"scand","southcarolina":"scarolina","school":
"","ms":"middle","science":"sci","scientific":"sci","scotland":"scotl",
"scripture":"script","sculpture":"sculpt","southdakota":"sdakota",
"southeastern":"se","southeast":"se","seismology":"seismol",
"selected":"sel","selectcommittee":"selcomm","selection":"select",
"september":"sept","series":"ser","sermon":"serm","session":"sess",
"settlement":"settlem","several":"sev","shakespeare":"shakes",
"shepherd":"sheph","shetland":"shetl","shropshire":"shropsh",
"singular":"sing","society":"soc","sociology":"sociol","sociological"
:"sociol","somerset":"som","songofsolomon":"songofsol","sonnet":
"sonn","spelling":"sp","spanish":"span","specifically":"spec",
"special":"spec","specimen":"spec","specification":"specif",
"spectroscopy":"spectrosc","saints":"ss","saint":"st","street":"st",
"drive":"dr","fundamental":"","acade":"acad",
"staffordshire":"staff","standard":"stand","statistical":"stat",
"stockexchange":"stockexch","strong":"str","stratigraphy":"stratigr",
"stratigraphical":"stratigr","structure":"struct","structural":
"struct","scottishtextsociety":"sts","studies":"stud","subject":
"subj","subjunctive":"subj","subordinate":"subord",
"subordinateclause":"subordcl","subscription":"subscr","subsequent":
"subseq","substantive":"subst","suffix":"suff","suffolk":"suff",
"superlative":"superl","supplement":"suppl","supplementary":"suppl",
"supplication":"supplic","suppression":"suppress","surgery":"surg",
"surgical":"surg","survey":"surv","surveying":"surv","susanna":"sus",
"subverbo":"sv","undertheword":"sv","southwestern":"sw","southwest":
"sw","syllable":"syll","symmetrical":"symmetr","symposium":"symp",
"system":"syst","tense":"t","taxonomy":"taxon","taxonomic":"taxon",
"technical":"techn","technology":"technol","technological":"technol",
"telegraph":"tel","telecommunications":"telecomm","telegraphy":
"telegr","telegraphic":"telegr","telephony":"teleph","telephonic":
"teleph","teratology":"teratol","terminology":"terminol",
"terminological":"terminol","terrestrial":"terrestr","testament":
"test","textbook":"textbk","theatre":"theat","theatrical":"theat",
"theology":"theol","theological":"theol","theoretical":"theoret",
"thermonuclear":"thermonucl","thesaurus":"thes","thessalonians":
"thess","timothy":"tim","titus":"tit","the":"","topography":"topogr",
"topographic":"topogr","translation":"tr","translating":"tr",
"tradition":"trad","traditional":"trad","tragedy":"trag","transitive"
:"trans","transaction":"trans","transferredsense":"transf",
"transubstantiation":"transubstant","travel":"trav","treasurer":
"treas","treasury":"treas","treatise":"treat","treatment":"treatm",
"tribune":"trib","trigonometry":"trig","tropical":"trop",
"troublesome":"troub","typography":"typog","unitedkingdom":"uk",
"ultimately":"ult","university":"univ","unknown":"unkn","unnatural":
"unnat","unofficial":"unoffic","unstressed":"unstr","urinary":"urin",
"unitedstates":"us","unitedstatesairforce":"usaf",
"unionofsovietsocialistrepublics":"ussr","usually":"usu",
"utilitarian":"utilit","verb":"v","virginia":"va","vacation":"vac",
"valediction":"valedict","variant":"var","variants":"varr","verbal":
"vbl","verbalnoun":"vbln","verbalnouns":"vblns","verbs":"vbs",
"vegetable":"veg","vegetablephysiology":"vegphys","venetian":"venet",
"vertebrate":"vertebr","veterinary":"vet","veterinaryscience":"vet",
"veterinarymedicine":"vetmed","veterinarypathology":"vetpath",
"veterinarysurgery":"vetsurg","victoria":"vic","vindication":"vind",
"vindicated":"vind","virgin":"virg","virology":"virol","videlicet":
"viz","namely":"viz","vocabulary":"voc","volume":"vol","volumes":
"vols","voyage":"voy","vulgar":"vulg","vulgate":"vulg","west":"w",
"western":"w","westafrica":"wafr","warwickshire":"warwicksh","word":
"wd","westminster":"westm","westmoreland":"westmld","william":"will",
"wiltshire":"wilts","westindies":"wind","westindian":"wind",
"wisconsin":"wis","wisdom":"wisd","wisdomofsolomon":"wisd","weak":
"wk","week":"wk","work":"wk","weekly":"wkly","works":"wks",
"wonderful":"wonderf","worcestershire":"worc","writing":"writ",
"westvirginia":"wva","yearbook":"yearbk","young":"yng","yorkshire":
"yorks","year":"yr","years":"yrs","zechariah":"zech","zeitschrift":
"zeitschr","zephaniah":"zeph","zoogeography":"zoogeogr","zoology":
"zool","zoological":"zool","charter":""}',true);
