<?php

return array(
	"package"=>array(
		"name"=>"YibblePoint",
		"email"=>"",
		"phone"=>"",
		"runOnStart"=>array(),
		"userCredits"=>true,
		"creditGracePeriod"=>7,
		"creditAllowance"=>2000,
		"creditAllowanceInterval"=>28
	),
	"backupEnabled"=>false,
	"updater"=>"http://www.yibbleware.com/j/YibblePoint/",
	"root"=>realpath(dirname(__FILE__)."/.."),
	"noEfx"=>false,
	"dev"=>array(
		"debug"=>false,
		"netDebug"=>false,
		"logDispatcher"=>false,
		"verbose"=>false,
		"errorTypes"=>E_ERROR | E_WARNING | E_PARSE | E_NOTICE | E_USER_ERROR | E_USER_WARNING,
		"maxErrBuffLen"=>1024*1024
	),
	"db"=>array(
		"initializeIfNonExistent"=>true,
		"type"=>"mysql",
		"server"=>"localhost",
		"prefix"=>""
	),
	"security"=>array(
		"keyFile"=>".slKey"
	),
	"web"=>array(
		"template"=>"yibui",
		"wysiwgEditor"=>false,
		"useTrailingSlash"=>true
	),
	"core"=>array(
		"theme"=>"default"
	),
	"sep"=>" - ",
	"preferences"=>array(
		"autoSave"=>false
	),
	"international"=>array(
		"country"=>"us",
		"language"=>"en-us",
		//"language"=>"es-mx",
		"dateOrder"=>"mdy",
		"date"=>"n/j/Y",
		"month"=>"M Y",
		"year"=>"Y",
		"time"=>"g:ia",
		"date-time"=>"n/j/Y g:ia"
	),
	"thirdparty"=>array(
		"phpqrcode"=>array(
			"name"=>"PHP QR Code",
			"desc"=>"PHP QR Code is open source (LGPL) library for generating QR Code, 2-dimensional barcode. Based on libqrencode C library, provides API for creating QR Code barcode images (PNG, JPEG thanks to GD2). Implemented purely in PHP, with no external dependencies (except GD2 if needed).",
			"relev"=>"",
			"include"=>"qrlib.php",
			"url"=>"http://phpqrcode.sourceforge.net/"
		),
		"PHPMailer"=>array(
			"name"=>"PHPMailer",
			"desc"=>"PHPMailer is a Full Featured Email Transfer Class for PHP",
			"relev"=>"",
			"include"=>"class.phpmailer.php",
			"packageDir"=>"libphp-phpmailer",
			"className"=>"PHPMailer",
			"unneeded"=>array("docs","examples","test","test_script"), 
			"url"=>"https://github.com/PHPMailer/PHPMailer",
			"required"=>true
		),
		"minify"=>array(
			"name"=>"minify",
			"desc"=>'<p>Minify is a PHP5 app that helps you follow several of Yahoo!&#x27;s <a href="http://developer.yahoo.com/performance/index.html#rules" rel="nofollow">Rules for High Performance Web Sites</a>. </p><p>It combines multiple CSS or Javascript files, removes unnecessary whitespace and comments, and serves them with gzip encoding and optimal client-side cache headers. </p>',
			"relev"=>"",
			"include"=>"min/lib/Minify.php",
			"setIncudePath"=>true,
			"url"=>"http://code.google.com/p/minify/"
		),
		"xmlapi-php-master"=>array(
			"name"=>"xmlapi-php",
			"desc"=>"A PHP Class for Interacting with cPanel's XML-API",
			"relev"=>"",
			"include"=>"xmlapi.php",
			"unneeded"=>array("Examples","Tests"),
			"url"=>"https://github.com/CpanelInc/xmlapi-php"
		),
		"php-ico-master"=>array(
			"name"=>"PHP ICO",
			"desc"=>"PHP ICO provides an easy-to-use PHP class that can be used to generate valid ICO files. Note that these are not simply BMP, GIF, or PNG formatted images with an extension of ico, the images generated by this class are fully valid ICO-formatted image files.",
			"relev"=>"",
			"include"=>"class-php-ico.php",
			"url"=>"https://github.com/chrisbliss18/php-ico"
		),
		"fpdf"=>array(
			"name"=>"FPDF",
			"desc"=>"FPDF is a PHP class which allows to generate PDF files with pure PHP, that is to say without using the PDFlib library. F from FPDF stands for Free: you may use it for any kind of usage and modify it to suit your needs.",
			"relev"=>"",
			"include"=>"fpdf.php",
			"unneeded"=>array("doc","tutorial"),
			"url"=>"http://www.fpdf.org/"
		),
		"Mobile-Detect"=>array(
			"name"=>"Mobile_Detect",
			"desc"=>"Mobile_Detect is a lightweight PHP class for detecting mobile devices. It uses the user-agent string combined with specific HTTP headers to detect the mobile environment.",
			"relev"=>"",
			"unneeded"=>array("examples"),
			"include"=>"Mobile_Detect.php",
			"url"=>"https://code.google.com/p/php-mobile-detect/"
		),
		"PhpUserAgent-master"=>array(
			"name"=>"PHP User Agent",
			"desc"=>"Simple, streamlined PHP user-agent parser.",
			"relev"=>"",
			"include"=>"Source/UserAgentParser.php",
			"url"=>"https://github.com/donatj/PhpUserAgent"
		),
		"country-list-master"=>array(
			"name"=>"Country List",
			"desc"=>"List of all countries with names and ISO 3166-1 codes in all languages and all data formats.",
			"relev"=>"",
			"url"=>"https://github.com/umpirsky/country-list",
			"required"=>true
		),
		"bootstrap"=>array(
			"name"=>"Bootstrap",
			"desc"=>"Sleek, intuitive, and powerful mobile first front-end framework for faster and easier web development.",
			"relev"=>"",
			"url"=>"http://getbootstrap.com/"
		),
		"SEOstats"=>array(
			"name"=>"SEO Stats",
			"desc"=>"SEOstats is a powerful open source tool to get a lot of SEO relevant data such as detailed backlink analyses, keyword and traffic statistics, website trends, page authority, the Google Pagerank, the Alexa Trafficrank and much more. Therefore SEOstats gathers data from Google, Yahoo, Bing, Majesticseo, SEOmoz, Alexa, Facebook and Twitter.",
			"relev"=>"",
			"unneeded"=>array("example"),
			"url"=>"https://code.google.com/p/seostats/",
			"include"=>"vendor/autoload.php"
		),
		"codemirror"=>array(
			"name"=>"CodeMirror",
			"desc"=>"CodeMirror is a code-editor component that can be embedded in Web pages.",
			"relev"=>"",
			"unneeded"=>array("demo","test"),
			"url"=>"http://codemirror.net/"
		),
		"Highcharts"=>array(
			"name"=>"Highcharts",
			"desc"=>"Highcharts is a charting library written in pure JavaScript, offering an easy way of adding interactive charts to your web site or web application. Highcharts currently supports line, spline, area, areaspline, column, bar, pie, scatter, angular gauges, arearange, areasplinerange, columnrange, bubble, box plot, error bars, funnel, waterfall and polar chart types.",
			"relev"=>"",
			"js"=>array("js/adapters/standalone-framework.js","js/highcharts.js"),
			"unneeded"=>array("examples"),
			"url"=>"http://www.highcharts.com/download"
		),
	),
	"net"=>array(
		"pollFrequencyMin"=>1,
		"pollFrequencyMax"=>5,
		"APIPollFrequencyMax"=>15,
	),
	"cleanup"=>array(
		"mininumTmpLife"=>600,
		"userTmpDataLife"=>86400,
		"sessionMaxLife"=>20*86400
	),
	"communication"=>array(
		"smtp"=>array(
			"Host"=>"localhost",
			"SMTPAuth"=>false,
			"Port"=>25,
			"Username"=>false,
			"Password"=>false
		),
		"defaultFrom"=>array(
			"name"=>"No Reply",
			"email"=>isset($_SERVER["SERVER_NAME"])?"noreply@".$_SERVER["SERVER_NAME"]:""
		)
	)
);
