<?php

return array(
	"coreTable"=>true,
	"name"=>"en-us|Campaign Activity",
	"singleName"=>"en-us|Campaign Activity",
	"linkingVerb"=>"en-us|is",
	"table"=>"db/campaignAction",
	"key"=>"id",
	"displayName"=>array("item.action"),
	"nameField"=>"action",
	"orderby"=>"ts",
	"orderdir"=>"desc",
	"userField"=>"userId",
	"showExtraData"=>"true",
	"extraDataLabels"=>array(
		"reason"=>"en-us|Reason",
		"category"=>"en-us|Category"
	),
	"fields"=>array(
		"campaignId"=>array(
			"label"=>"en-us|Campaign",
			"type"=>"object",
			"viewable"=>false,
			"readOnly"=>true,
			"ref"=>"db/campaigns"
		),
		"componentId"=>array(
			"label"=>"en-us|Component",
			"type"=>"object",
			"ref"=>"db/campaignComponents",
			"readOnly"=>true
		),
		"queueId"=>array(
			"label"=>"en-us|Queue",
			"type"=>"object",
			"viewable"=>false,
			"editable"=>false,
			"ref"=>"db/blastQueue"
		),
		"contactId"=>array(
			"label"=>"en-us|Contact",
			"type"=>"object",
			"ref"=>"db/contacts",
			"readOnly"=>true
		),
		"action"=>array(
			"label"=>"en-us|Action",
			"searchable"=>true,
			"type"=>"select",
			"options"=>array(
				"send"=>"en-us|Send",
				"view"=>"en-us|View",
				"click"=>"en-us|Click",
				"fail"=>"en-us|Fail",
				"unsubscribe"=>"en-us|Unsubscribe"
			),
			"readOnly"=>true	
		),
		"ts"=>array(
			"label"=>"en-us|Timestamp",
			"type"=>"date",
			"readOnly"=>true
		),
		"revenue"=>array(
			"label"=>"en-us|Revenue",
			"type"=>"credits",
			"default"=>"",
			"editable"=>false,
			"total"=>"sum"
		),
		"unique"=>array(
			"viewable"=>false,
			"editable"=>false
		)
	)		
);
