sl.mimeList = /*MIME_LIST*/ [["en-us|3D Crossword Plugin","application/vnd.hzn-3d-crossword","x3d"],
["en-us|3GP","video/3gpp","3gp"],
["en-us|3GP2","video/3gpp2","3g2"],
["en-us|3GPP MSEQ File","application/vnd.mseq","mseq"],
["en-us|3M Post It Notes","application/vnd.3m.post-it-notes","pwn"],
["en-us|3rd Generation Partnership Project - Pic Large","application/vnd.3gpp.pic-bw-large","plb"],
["en-us|3rd Generation Partnership Project - Pic Small","application/vnd.3gpp.pic-bw-small","psb"],
["en-us|3rd Generation Partnership Project - Pic Var","application/vnd.3gpp.pic-bw-var","pvb"],
["en-us|3rd Generation Partnership Project - Transaction Capabilities Application Part","application/vnd.3gpp2.tcap","tcap"],
["en-us|7-Zip","application/x-7z-compressed","7z"],
["en-us|AbiWord","application/x-abiword","abw"],
["en-us|Ace Archive","application/x-ace-compressed","ace"],
["en-us|Active Content Compression","application/vnd.americandynamics.acc","acc"],
["en-us|ACU Cobol","application/vnd.acucobol","acu"],
["en-us|ACU Cobol","application/vnd.acucorp","atc"],
["en-us|Adaptive differential pulse-code modulation","audio/adpcm","adp"],
["en-us|Adobe (Macropedia) Authorware - Binary File","application/x-authorware-bin","aab"],
["en-us|Adobe (Macropedia) Authorware - Map","application/x-authorware-map","aam"],
["en-us|Adobe (Macropedia) Authorware - Segment File","application/x-authorware-seg","aas"],
["en-us|Adobe AIR Application","application/vnd.adobe.air-application-installer-package+zip","air"],
["en-us|Adobe Flash","application/x-shockwave-flash","swf"],
["en-us|Adobe Flex Project","application/vnd.adobe.fxp","fxp"],
["en-us|Adobe Portable Document Format","application/pdf","pdf"],
["en-us|Adobe PostScript Printer Description File Format","application/vnd.cups-ppd","ppd"],
["en-us|Adobe Shockwave Player","application/x-director","dir"],
["en-us|Adobe XML Data Package","application/vnd.adobe.xdp+xml","xdp"],
["en-us|Adobe XML Forms Data Format","application/vnd.adobe.xfdf","xfdf"],
["en-us|Advanced Audio Coding (AAC)","audio/x-aac","aac"],
["en-us|Ahead AIR Application","application/vnd.ahead.space","ahead"],
["en-us|AirZip FileSECURE","application/vnd.airzip.filesecure.azf","azf"],
["en-us|AirZip FileSECURE","application/vnd.airzip.filesecure.azs","azs"],
["en-us|Amazon Kindle eBook format","application/vnd.amazon.ebook","azw"],
["en-us|AmigaDE","application/vnd.amiga.ami","ami"],
["en-us|Andrew Toolkit","application/andrew-inset","N/A"],
["en-us|Android Package Archive","application/vnd.android.package-archive","apk"],
["en-us|ANSER-WEB Terminal Client - Certificate Issue","application/vnd.anser-web-certificate-issue-initiation","cii"],
["en-us|ANSER-WEB Terminal Client - Web Funds Transfer","application/vnd.anser-web-funds-transfer-initiation","fti"],
["en-us|Antix Game Player","application/vnd.antix.game-component","atx"],
["en-us|Apple Installer Package","application/vnd.apple.installer+xml","mpkg"],
["en-us|Applixware","application/applixware","aw"],
["en-us|Archipelago Lesson Player","application/vnd.hhe.lesson-player","les"],
["en-us|Arista Networks Software Image","application/vnd.aristanetworks.swi","swi"],
["en-us|Assembler Source File","text/x-asm","s"],
["en-us|Atom Publishing Protocol","application/atomcat+xml","atomcat"],
["en-us|Atom Publishing Protocol Service Document","application/atomsvc+xml","atomsvc"],
["en-us|Atom Syndication Format","application/atom+xml","atom, .xml"],
["en-us|Attribute Certificate","application/pkix-attr-cert","ac"],
["en-us|Audio Interchange File Format","audio/x-aiff","aif"],
["en-us|Audio Video Interleave (AVI)","video/x-msvideo","avi"],
["en-us|Audiograph","application/vnd.audiograph","aep"],
["en-us|AutoCAD DXF","image/vnd.dxf","dxf"],
["en-us|Autodesk Design Web Format (DWF)","model/vnd.dwf","dwf"],
["en-us|BAS Partitur Format","text/plain-bas","par"],
["en-us|Binary CPIO Archive","application/x-bcpio","bcpio"],
["en-us|Binary Data","application/octet-stream","bin"],
["en-us|Bitmap Image File","image/bmp","bmp"],
["en-us|BitTorrent","application/x-bittorrent","torrent"],
["en-us|Blackberry COD File","application/vnd.rim.cod","cod"],
["en-us|Blueice Research Multipass","application/vnd.blueice.multipass","mpm"],
["en-us|BMI Drawing Data Interchange","application/vnd.bmi","bmi"],
["en-us|Bourne Shell Script","application/x-sh","sh"],
["en-us|BTIF","image/prs.btif","btif"],
["en-us|BusinessObjects","application/vnd.businessobjects","rep"],
["en-us|Bzip Archive","application/x-bzip","bz"],
["en-us|Bzip2 Archive","application/x-bzip2","bz2"],
["en-us|C Shell Script","application/x-csh","csh"],
["en-us|C Source File","text/x-c","c"],
["en-us|CambridgeSoft Chem Draw","application/vnd.chemdraw+xml","cdxml"],
["en-us|Cascading Style Sheets (CSS)","text/css","css"],
["en-us|ChemDraw eXchange file","chemical/x-cdx","cdx"],
["en-us|Chemical Markup Language","chemical/x-cml","cml"],
["en-us|Chemical Style Markup Language","chemical/x-csml","csml"],
["en-us|CIM Database","application/vnd.contact.cmsg","cdbcmsg"],
["en-us|Claymore Data Files","application/vnd.claymore","cla"],
["en-us|Clonk Game","application/vnd.clonk.c4group","c4g"],
["en-us|Close Captioning - Subtitle","image/vnd.dvb.subtitle","sub"],
["en-us|Cloud Data Management Interface (CDMI) - Capability","application/cdmi-capability","cdmia"],
["en-us|Cloud Data Management Interface (CDMI) - Contaimer","application/cdmi-container","cdmic"],
["en-us|Cloud Data Management Interface (CDMI) - Domain","application/cdmi-domain","cdmid"],
["en-us|Cloud Data Management Interface (CDMI) - Object","application/cdmi-object","cdmio"],
["en-us|Cloud Data Management Interface (CDMI) - Queue","application/cdmi-queue","cdmiq"],
["en-us|ClueTrust CartoMobile - Config","application/vnd.cluetrust.cartomobile-config","c11amc"],
["en-us|ClueTrust CartoMobile - Config Package","application/vnd.cluetrust.cartomobile-config-pkg","c11amz"],
["en-us|CMU Image","image/x-cmu-raster","ras"],
["en-us|COLLADA","model/vnd.collada+xml","dae"],
["en-us|Comma-Seperated Values","text/csv","csv"],
["en-us|Compact Pro","application/mac-compactpro","cpt"],
["en-us|Compiled Wireless Markup Language (WMLC)","application/vnd.wap.wmlc","wmlc"],
["en-us|Computer Graphics Metafile","image/cgm","cgm"],
["en-us|CoolTalk","x-conference/x-cooltalk","ice"],
["en-us|Corel Metafile Exchange (CMX)","image/x-cmx","cmx"],
["en-us|CorelXARA","application/vnd.xara","xar"],
["en-us|CosmoCaller","application/vnd.cosmocaller","cmc"],
["en-us|CPIO Archive","application/x-cpio","cpio"],
["en-us|CrickSoftware - Clicker","application/vnd.crick.clicker","clkx"],
["en-us|CrickSoftware - Clicker - Keyboard","application/vnd.crick.clicker.keyboard","clkk"],
["en-us|CrickSoftware - Clicker - Palette","application/vnd.crick.clicker.palette","clkp"],
["en-us|CrickSoftware - Clicker - Template","application/vnd.crick.clicker.template","clkt"],
["en-us|CrickSoftware - Clicker - Wordbank","application/vnd.crick.clicker.wordbank","clkw"],
["en-us|Critical Tools - PERT Chart EXPERT","application/vnd.criticaltools.wbs+xml","wbs"],
["en-us|CryptoNote","application/vnd.rig.cryptonote","cryptonote"],
["en-us|Crystallographic Interchange Format","chemical/x-cif","cif"],
["en-us|CrystalMaker Data Format","chemical/x-cmdf","cmdf"],
["en-us|CU-SeeMe","application/cu-seeme","cu"],
["en-us|CU-Writer","application/prs.cww","cww"],
["en-us|Curl - Applet","text/vnd.curl","curl"],
["en-us|Curl - Detached Applet","text/vnd.curl.dcurl","dcurl"],
["en-us|Curl - Manifest File","text/vnd.curl.mcurl","mcurl"],
["en-us|Curl - Source Code","text/vnd.curl.scurl","scurl"],
["en-us|CURL Applet","application/vnd.curl.car","car"],
["en-us|CURL Applet","application/vnd.curl.pcurl","pcurl"],
["en-us|CustomMenu","application/vnd.yellowriver-custom-menu","cmp"],
["en-us|Data Structure for the Security Suitability of Cryptographic Algorithms","application/dssc+der","dssc"],
["en-us|Data Structure for the Security Suitability of Cryptographic Algorithms","application/dssc+xml","xdssc"],
["en-us|Debian Package","application/x-debian-package","deb"],
["en-us|DECE Audio","audio/vnd.dece.audio","uva"],
["en-us|DECE Graphic","image/vnd.dece.graphic","uvi"],
["en-us|DECE High Definition Video","video/vnd.dece.hd","uvh"],
["en-us|DECE Mobile Video","video/vnd.dece.mobile","uvm"],
["en-us|DECE MP4","video/vnd.uvvu.mp4","uvu"],
["en-us|DECE PD Video","video/vnd.dece.pd","uvp"],
["en-us|DECE SD Video","video/vnd.dece.sd","uvs"],
["en-us|DECE Video","video/vnd.dece.video","uvv"],
["en-us|Device Independent File Format (DVI)","application/x-dvi","dvi"],
["en-us|Digital Siesmograph Networks - SEED Datafiles","application/vnd.fdsn.seed","seed"],
["en-us|Digital Talking Book","application/x-dtbook+xml","dtb"],
["en-us|Digital Talking Book - Resource File","application/x-dtbresource+xml","res"],
["en-us|Digital Video Broadcasting","application/vnd.dvb.ait","ait"],
["en-us|Digital Video Broadcasting","application/vnd.dvb.service","svc"],
["en-us|Digital Winds Music","audio/vnd.digital-winds","eol"],
["en-us|DjVu","image/vnd.djvu","djvu"],
["en-us|Document Type Definition","application/xml-dtd","dtd"],
["en-us|Dolby Meridian Lossless Packing","application/vnd.dolby.mlp","mlp"],
["en-us|Doom Video Game","application/x-doom","wad"],
["en-us|DPGraph","application/vnd.dpgraph","dpg"],
["en-us|DRA Audio","audio/vnd.dra","dra"],
["en-us|DreamFactory","application/vnd.dreamfactory","dfac"],
["en-us|DTS Audio","audio/vnd.dts","dts"],
["en-us|DTS High Definition Audio","audio/vnd.dts.hd","dtshd"],
["en-us|DWG Drawing","image/vnd.dwg","dwg"],
["en-us|DynaGeo","application/vnd.dynageo","geo"],
["en-us|ECMAScript","application/ecmascript","es"],
["en-us|EcoWin Chart","application/vnd.ecowin.chart","mag"],
["en-us|EDMICS 2000","image/vnd.fujixerox.edmics-mmr","mmr"],
["en-us|EDMICS 2000","image/vnd.fujixerox.edmics-rlc","rlc"],
["en-us|Efficient XML Interchange","application/exi","exi"],
["en-us|EFI Proteus","application/vnd.proteus.magazine","mgz"],
["en-us|Electronic Publication","application/epub+zip","epub"],
["en-us|Email Message","message/rfc822","eml"],
["en-us|Enliven Viewer","application/vnd.enliven","nml"],
["en-us|Express by Infoseek","application/vnd.is-xpr","xpr"],
["en-us|eXtended Image File Format (XIFF)","image/vnd.xiff","xif"],
["en-us|Extensible Forms Description Language","application/vnd.xfdl","xfdl"],
["en-us|Extensible MultiModal Annotation","application/emma+xml","emma"],
["en-us|EZPix Secure Photo Album","application/vnd.ezpix-album","ez2"],
["en-us|EZPix Secure Photo Album","application/vnd.ezpix-package","ez3"],
["en-us|FAST Search & Transfer ASA","image/vnd.fst","fst"],
["en-us|FAST Search & Transfer ASA","video/vnd.fvt","fvt"],
["en-us|FastBid Sheet","image/vnd.fastbidsheet","fbs"],
["en-us|FCS Express Layout Link","application/vnd.denovo.fcselayout-link","fe_launch"],
["en-us|Flash Video","video/x-f4v","f4v"],
["en-us|Flash Video","video/x-flv","flv"],
["en-us|FlashPix","image/vnd.fpx","fpx"],
["en-us|FlashPix","image/vnd.net-fpx","npx"],
["en-us|FLEXSTOR","text/vnd.fmi.flexstor","flx"],
["en-us|FLI/FLC Animation Format","video/x-fli","fli"],
["en-us|FluxTime Clip","application/vnd.fluxtime.clip","ftc"],
["en-us|Forms Data Format","application/vnd.fdf","fdf"],
["en-us|Fortran Source File","text/x-fortran","f"],
["en-us|FrameMaker Interchange Format","application/vnd.mif","mif"],
["en-us|FrameMaker Normal Format","application/vnd.framemaker","fm"],
["en-us|FreeHand MX","image/x-freehand","fh"],
["en-us|Friendly Software Corporation","application/vnd.fsc.weblaunch","fsc"],
["en-us|Frogans Player","application/vnd.frogans.fnc","fnc"],
["en-us|Frogans Player","application/vnd.frogans.ltf","ltf"],
["en-us|Fujitsu - Xerox 2D CAD Data","application/vnd.fujixerox.ddd","ddd"],
["en-us|Fujitsu - Xerox DocuWorks","application/vnd.fujixerox.docuworks","xdw"],
["en-us|Fujitsu - Xerox DocuWorks Binder","application/vnd.fujixerox.docuworks.binder","xbd"],
["en-us|Fujitsu Oasys","application/vnd.fujitsu.oasys","oas"],
["en-us|Fujitsu Oasys","application/vnd.fujitsu.oasys2","oa2"],
["en-us|Fujitsu Oasys","application/vnd.fujitsu.oasys3","oa3"],
["en-us|Fujitsu Oasys","application/vnd.fujitsu.oasysgp","fg5"],
["en-us|Fujitsu Oasys","application/vnd.fujitsu.oasysprs","bh2"],
["en-us|FutureSplash Animator","application/x-futuresplash","spl"],
["en-us|FuzzySheet","application/vnd.fuzzysheet","fzs"],
["en-us|G3 Fax Image","image/g3fax","g3"],
["en-us|GameMaker ActiveX","application/vnd.gmx","gmx"],
["en-us|Gen-Trix Studio","model/vnd.gtw","gtw"],
["en-us|Genomatix Tuxedo Framework","application/vnd.genomatix.tuxedo","txd"],
["en-us|GeoGebra","application/vnd.geogebra.file","ggb"],
["en-us|GeoGebra","application/vnd.geogebra.tool","ggt"],
["en-us|Geometric Description Language (GDL)","model/vnd.gdl","gdl"],
["en-us|GeoMetry Explorer","application/vnd.geometry-explorer","gex"],
["en-us|GEONExT and JSXGraph","application/vnd.geonext","gxt"],
["en-us|GeoplanW","application/vnd.geoplan","g2w"],
["en-us|GeospacW","application/vnd.geospace","g3w"],
["en-us|Ghostscript Font","application/x-font-ghostscript","gsf"],
["en-us|Glyph Bitmap Distribution Format","application/x-font-bdf","bdf"],
["en-us|GNU Tar Files","application/x-gtar","gtar"],
["en-us|GNU Texinfo Document","application/x-texinfo","texinfo"],
["en-us|Gnumeric","application/x-gnumeric","gnumeric"],
["en-us|Google Earth - KML","application/vnd.google-earth.kml+xml","kml"],
["en-us|Google Earth - Zipped KML","application/vnd.google-earth.kmz","kmz"],
["en-us|GrafEq","application/vnd.grafeq","gqf"],
["en-us|Graphics Interchange Format","image/gif","gif"],
["en-us|Graphviz","text/vnd.graphviz","gv"],
["en-us|Groove - Account","application/vnd.groove-account","gac"],
["en-us|Groove - Help","application/vnd.groove-help","ghf"],
["en-us|Groove - Identity Message","application/vnd.groove-identity-message","gim"],
["en-us|Groove - Injector","application/vnd.groove-injector","grv"],
["en-us|Groove - Tool Message","application/vnd.groove-tool-message","gtm"],
["en-us|Groove - Tool Template","application/vnd.groove-tool-template","tpl"],
["en-us|Groove - Vcard","application/vnd.groove-vcard","vcg"],
["en-us|H.261","video/h261","h261"],
["en-us|H.263","video/h263","h263"],
["en-us|H.264","video/h264","h264"],
["en-us|Hewlett Packard Instant Delivery","application/vnd.hp-hpid","hpid"],
["en-us|Hewlett-Packard's WebPrintSmart","application/vnd.hp-hps","hps"],
["en-us|Hierarchical Data Format","application/x-hdf","hdf"],
["en-us|Hit'n'Mix","audio/vnd.rip","rip"],
["en-us|Homebanking Computer Interface (HBCI)","application/vnd.hbci","hbci"],
["en-us|HP Indigo Digital Press - Job Layout Languate","application/vnd.hp-jlyt","jlt"],
["en-us|HP Printer Command Language","application/vnd.hp-pcl","pcl"],
["en-us|HP-GL/2 and HP RTL","application/vnd.hp-hpgl","hpgl"],
["en-us|HV Script","application/vnd.yamaha.hv-script","hvs"],
["en-us|HV Voice Dictionary","application/vnd.yamaha.hv-dic","hvd"],
["en-us|HV Voice Parameter","application/vnd.yamaha.hv-voice","hvp"],
["en-us|Hydrostatix Master Suite","application/vnd.hydrostatix.sof-data","sfd-hdstx"],
["en-us|Hyperstudio","application/hyperstudio","stk"],
["en-us|Hypertext Application Language","application/vnd.hal+xml","hal"],
["en-us|HyperText Markup Language (HTML)","text/html","html"],
["en-us|IBM DB2 Rights Manager","application/vnd.ibm.rights-management","irm"],
["en-us|IBM Electronic Media Management System - Secure Container","application/vnd.ibm.secure-container","sc"],
["en-us|iCalendar","text/calendar","ics"],
["en-us|ICC profile","application/vnd.iccprofile","icc"],
["en-us|Icon Image","image/x-icon","ico"],
["en-us|igLoader","application/vnd.igloader","igl"],
["en-us|Image Exchange Format","image/ief","ief"],
["en-us|ImmerVision PURE Players","application/vnd.immervision-ivp","ivp"],
["en-us|ImmerVision PURE Players","application/vnd.immervision-ivu","ivu"],
["en-us|IMS Networks","application/reginfo+xml","rif"],
["en-us|In3D - 3DML","text/vnd.in3d.3dml","3dml"],
["en-us|In3D - 3DML","text/vnd.in3d.spot","spot"],
["en-us|Initial Graphics Exchange Specification (IGES)","model/iges","igs"],
["en-us|Interactive Geometry Software","application/vnd.intergeo","i2g"],
["en-us|Interactive Geometry Software Cinderella","application/vnd.cinderella","cdy"],
["en-us|Intercon FormNet","application/vnd.intercon.formnet","xpw"],
["en-us|International Society for Advancement of Cytometry","application/vnd.isac.fcs","fcs"],
["en-us|Internet Protocol Flow Information Export","application/ipfix","ipfix"],
["en-us|Internet Public Key Infrastructure - Certificate","application/pkix-cert","cer"],
["en-us|Internet Public Key Infrastructure - Certificate Management Protocole","application/pkixcmp","pki"],
["en-us|Internet Public Key Infrastructure - Certificate Revocation Lists","application/pkix-crl","crl"],
["en-us|Internet Public Key Infrastructure - Certification Path","application/pkix-pkipath","pkipath"],
["en-us|IOCOM Visimeet","application/vnd.insors.igm","igm"],
["en-us|IP Unplugged Roaming Client","application/vnd.ipunplugged.rcprofile","rcprofile"],
["en-us|iRepository / Lucidoc Editor","application/vnd.irepository.package+xml","irp"],
["en-us|J2ME App Descriptor","text/vnd.sun.j2me.app-descriptor","jad"],
["en-us|Java Archive","application/java-archive","jar"],
["en-us|Java Bytecode File","application/java-vm","class"],
["en-us|Java Network Launching Protocol","application/x-java-jnlp-file","jnlp"],
["en-us|Java Serialized Object","application/java-serialized-object","ser"],
["en-us|Java Source File","text/x-java-source,java","java"],
["en-us|JavaScript","application/javascript","js"],
["en-us|JavaScript Object Notation (JSON)","application/json","json"],
["en-us|Joda Archive","application/vnd.joost.joda-archive","joda"],
["en-us|JPEG 2000 Compound Image File Format","video/jpm","jpm"],
["en-us|JPEG Image","image/jpeg","jpeg,jpg"],
["en-us|JPGVideo","video/jpeg","jpgv"],
["en-us|Kahootz","application/vnd.kahootz","ktz"],
["en-us|Karaoke on Chipnuts Chipsets","application/vnd.chipnuts.karaoke-mmd","mmd"],
["en-us|KDE KOffice Office Suite - Karbon","application/vnd.kde.karbon","karbon"],
["en-us|KDE KOffice Office Suite - KChart","application/vnd.kde.kchart","chrt"],
["en-us|KDE KOffice Office Suite - Kformula","application/vnd.kde.kformula","kfo"],
["en-us|KDE KOffice Office Suite - Kivio","application/vnd.kde.kivio","flw"],
["en-us|KDE KOffice Office Suite - Kontour","application/vnd.kde.kontour","kon"],
["en-us|KDE KOffice Office Suite - Kpresenter","application/vnd.kde.kpresenter","kpr"],
["en-us|KDE KOffice Office Suite - Kspread","application/vnd.kde.kspread","ksp"],
["en-us|KDE KOffice Office Suite - Kword","application/vnd.kde.kword","kwd"],
["en-us|Kenamea App","application/vnd.kenameaapp","htke"],
["en-us|Kidspiration","application/vnd.kidspiration","kia"],
["en-us|Kinar Applications","application/vnd.kinar","kne"],
["en-us|Kodak Storyshare","application/vnd.kodak-descriptor","sse"],
["en-us|Laser App Enterprise","application/vnd.las.las+xml","lasxml"],
["en-us|LaTeX","application/x-latex","latex"],
["en-us|Life Balance - Desktop Edition","application/vnd.llamagraphics.life-balance.desktop","lbd"],
["en-us|Life Balance - Exchange Format","application/vnd.llamagraphics.life-balance.exchange+xml","lbe"],
["en-us|Lightspeed Audio Lab","application/vnd.jam","jam"],
["en-us|Lotus 1-2-3","application/vnd.lotus-1-2-3","123"],
["en-us|Lotus Approach","application/vnd.lotus-approach","apr"],
["en-us|Lotus Freelance","application/vnd.lotus-freelance","pre"],
["en-us|Lotus Notes","application/vnd.lotus-notes","nsf"],
["en-us|Lotus Organizer","application/vnd.lotus-organizer","org"],
["en-us|Lotus Screencam","application/vnd.lotus-screencam","scm"],
["en-us|Lotus Wordpro","application/vnd.lotus-wordpro","lwp"],
["en-us|Lucent Voice","audio/vnd.lucent.voice","lvp"],
["en-us|M3U (Multimedia Playlist)","audio/x-mpegurl","m3u"],
["en-us|M4v","video/x-m4v","m4v"],
["en-us|Macintosh BinHex 4.0","application/mac-binhex40","hqx"],
["en-us|MacPorts Port System","application/vnd.macports.portpkg","portpkg"],
["en-us|MapGuide DBXML","application/vnd.osgeo.mapguide.package","mgp"],
["en-us|MARC Formats","application/marc","mrc"],
["en-us|MARC21 XML Schema","application/marcxml+xml","mrcx"],
["en-us|Material Exchange Format","application/mxf","mxf"],
["en-us|Mathematica Notebook Player","application/vnd.wolfram.player","nbp"],
["en-us|Mathematica Notebooks","application/mathematica","ma"],
["en-us|Mathematical Markup Language","application/mathml+xml","mathml"],
["en-us|Mbox database files","application/mbox","mbox"],
["en-us|MedCalc","application/vnd.medcalcdata","mc1"],
["en-us|Media Server Control Markup Language","application/mediaservercontrol+xml","mscml"],
["en-us|MediaRemote","application/vnd.mediastation.cdkey","cdkey"],
["en-us|Medical Waveform Encoding Format","application/vnd.mfer","mwf"],
["en-us|Melody Format for Mobile Platform","application/vnd.mfmp","mfm"],
["en-us|Mesh Data Type","model/mesh","msh"],
["en-us|Metadata Authority Description Schema","application/mads+xml","mads"],
["en-us|Metadata Encoding and Transmission Standard","application/mets+xml","mets"],
["en-us|Metadata Object Description Schema","application/mods+xml","mods"],
["en-us|Metalink","application/metalink4+xml","meta4"],
["en-us|Micosoft PowerPoint - Macro-Enabled Template File","application/vnd.ms-powerpoint.template.macroenabled.12","potm"],
["en-us|Micosoft Word - Macro-Enabled Document","application/vnd.ms-word.document.macroenabled.12","docm"],
["en-us|Micosoft Word - Macro-Enabled Template","application/vnd.ms-word.template.macroenabled.12","dotm"],
["en-us|Micro CADAM Helix D&D","application/vnd.mcd","mcd"],
["en-us|Micrografx","application/vnd.micrografx.flo","flo"],
["en-us|Micrografx iGrafx Professional","application/vnd.micrografx.igx","igx"],
["en-us|MICROSEC e-Szign¢","application/vnd.eszigno3+xml","es3"],
["en-us|Microsoft Access","application/x-msaccess","mdb"],
["en-us|Microsoft Advanced Systems Format (ASF)","video/x-ms-asf","asf"],
["en-us|Microsoft Application","application/x-msdownload","exe"],
["en-us|Microsoft Artgalry","application/vnd.ms-artgalry","cil"],
["en-us|Microsoft Cabinet File","application/vnd.ms-cab-compressed","cab"],
["en-us|Microsoft Class Server","application/vnd.ms-ims","ims"],
["en-us|Microsoft ClickOnce","application/x-ms-application","application"],
["en-us|Microsoft Clipboard Clip","application/x-msclip","clp"],
["en-us|Microsoft Document Imaging Format","image/vnd.ms-modi","mdi"],
["en-us|Microsoft Embedded OpenType","application/vnd.ms-fontobject","eot"],
["en-us|Microsoft Excel","application/vnd.ms-excel","xls"],
["en-us|Microsoft Excel - Add-In File","application/vnd.ms-excel.addin.macroenabled.12","xlam"],
["en-us|Microsoft Excel - Binary Workbook","application/vnd.ms-excel.sheet.binary.macroenabled.12","xlsb"],
["en-us|Microsoft Excel - Macro-Enabled Template File","application/vnd.ms-excel.template.macroenabled.12","xltm"],
["en-us|Microsoft Excel - Macro-Enabled Workbook","application/vnd.ms-excel.sheet.macroenabled.12","xlsm"],
["en-us|Microsoft Html Help File","application/vnd.ms-htmlhelp","chm"],
["en-us|Microsoft Information Card","application/x-mscardfile","crd"],
["en-us|Microsoft Learning Resource Module","application/vnd.ms-lrm","lrm"],
["en-us|Microsoft MediaView","application/x-msmediaview","mvb"],
["en-us|Microsoft Money","application/x-msmoney","mny"],
["en-us|Microsoft Office - OOXML - Presentation","application/vnd.openxmlformats-officedocument.presentationml.presentation","pptx"],
["en-us|Microsoft Office - OOXML - Presentation (Slide)","application/vnd.openxmlformats-officedocument.presentationml.slide","sldx"],
["en-us|Microsoft Office - OOXML - Presentation (Slideshow)","application/vnd.openxmlformats-officedocument.presentationml.slideshow","ppsx"],
["en-us|Microsoft Office - OOXML - Presentation Template","application/vnd.openxmlformats-officedocument.presentationml.template","potx"],
["en-us|Microsoft Office - OOXML - Spreadsheet","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","xlsx"],
["en-us|Microsoft Office - OOXML - Spreadsheet Teplate","application/vnd.openxmlformats-officedocument.spreadsheetml.template","xltx"],
["en-us|Microsoft Office - OOXML - Word Document","application/vnd.openxmlformats-officedocument.wordprocessingml.document","docx"],
["en-us|Microsoft Office - OOXML - Word Document Template","application/vnd.openxmlformats-officedocument.wordprocessingml.template","dotx"],
["en-us|Microsoft Office Binder","application/x-msbinder","obd"],
["en-us|Microsoft Office System Release Theme","application/vnd.ms-officetheme","thmx"],
["en-us|Microsoft OneNote","application/onenote","onetoc"],
["en-us|Microsoft PlayReady Ecosystem","audio/vnd.ms-playready.media.pya","pya"],
["en-us|Microsoft PlayReady Ecosystem Video","video/vnd.ms-playready.media.pyv","pyv"],
["en-us|Microsoft PowerPoint","application/vnd.ms-powerpoint","ppt"],
["en-us|Microsoft PowerPoint - Add-in file","application/vnd.ms-powerpoint.addin.macroenabled.12","ppam"],
["en-us|Microsoft PowerPoint - Macro-Enabled Open XML Slide","application/vnd.ms-powerpoint.slide.macroenabled.12","sldm"],
["en-us|Microsoft PowerPoint - Macro-Enabled Presentation File","application/vnd.ms-powerpoint.presentation.macroenabled.12","pptm"],
["en-us|Microsoft PowerPoint - Macro-Enabled Slide Show File","application/vnd.ms-powerpoint.slideshow.macroenabled.12","ppsm"],
["en-us|Microsoft Project","application/vnd.ms-project","mpp"],
["en-us|Microsoft Publisher","application/x-mspublisher","pub"],
["en-us|Microsoft Schedule+","application/x-msschedule","scd"],
["en-us|Microsoft Silverlight","application/x-silverlight-app","xap"],
["en-us|Microsoft Trust UI Provider - Certificate Trust Link","application/vnd.ms-pki.stl","stl"],
["en-us|Microsoft Trust UI Provider - Security Catalog","application/vnd.ms-pki.seccat","cat"],
["en-us|Microsoft Visio","application/vnd.visio","vsd"],
["en-us|Microsoft Windows Media","video/x-ms-wm","wm"],
["en-us|Microsoft Windows Media Audio","audio/x-ms-wma","wma"],
["en-us|Microsoft Windows Media Audio Redirector","audio/x-ms-wax","wax"],
["en-us|Microsoft Windows Media Audio/Video Playlist","video/x-ms-wmx","wmx"],
["en-us|Microsoft Windows Media Player Download Package","application/x-ms-wmd","wmd"],
["en-us|Microsoft Windows Media Player Playlist","application/vnd.ms-wpl","wpl"],
["en-us|Microsoft Windows Media Player Skin Package","application/x-ms-wmz","wmz"],
["en-us|Microsoft Windows Media Video","video/x-ms-wmv","wmv"],
["en-us|Microsoft Windows Media Video Playlist","video/x-ms-wvx","wvx"],
["en-us|Microsoft Windows Metafile","application/x-msmetafile","wmf"],
["en-us|Microsoft Windows Terminal Services","application/x-msterminal","trm"],
["en-us|Microsoft Word","application/msword","doc"],
["en-us|Microsoft Wordpad","application/x-mswrite","wri"],
["en-us|Microsoft Works","application/vnd.ms-works","wps"],
["en-us|Microsoft XAML Browser Application","application/x-ms-xbap","xbap"],
["en-us|Microsoft XML Paper Specification","application/vnd.ms-xpsdocument","xps"],
["en-us|MIDI - Musical Instrument Digital Interface","audio/midi","mid"],
["en-us|MiniPay","application/vnd.ibm.minipay","mpy"],
["en-us|MO:DCA-P","application/vnd.ibm.modcap","afp"],
["en-us|Mobile Information Device Profile","application/vnd.jcp.javame.midlet-rms","rms"],
["en-us|MobileTV","application/vnd.tmobile-livetv","tmo"],
["en-us|Mobipocket","application/x-mobipocket-ebook","prc"],
["en-us|Mobius Management Systems - Basket file","application/vnd.mobius.mbk","mbk"],
["en-us|Mobius Management Systems - Distribution Database","application/vnd.mobius.dis","dis"],
["en-us|Mobius Management Systems - Policy Definition Language File","application/vnd.mobius.plc","plc"],
["en-us|Mobius Management Systems - Query File","application/vnd.mobius.mqy","mqy"],
["en-us|Mobius Management Systems - Script Language","application/vnd.mobius.msl","msl"],
["en-us|Mobius Management Systems - Topic Index File","application/vnd.mobius.txf","txf"],
["en-us|Mobius Management Systems - UniversalArchive","application/vnd.mobius.daf","daf"],
["en-us|mod_fly / fly.cgi","text/vnd.fly","fly"],
["en-us|Mophun Certificate","application/vnd.mophun.certificate","mpc"],
["en-us|Mophun VM","application/vnd.mophun.application","mpn"],
["en-us|Motion JPEG 2000","video/mj2","mj2"],
["en-us|MPEG Audio","audio/mpeg","mpga"],
["en-us|MPEG Url","video/vnd.mpegurl","mxu"],
["en-us|MPEG Video","video/mpeg","mpeg"],
["en-us|MPEG-21","application/mp21","m21"],
["en-us|MPEG-4 Audio","audio/mp4","mp4a"],
["en-us|MPEG-4 Video","video/mp4","mp4"],
["en-us|MPEG4","application/mp4","mp4"],
["en-us|Multimedia Playlist Unicode","application/vnd.apple.mpegurl","m3u8"],
["en-us|MUsical Score Interpreted Code Invented for the ASCII designation of Notation","application/vnd.musician","mus"],
["en-us|Muvee Automatic Video Editing","application/vnd.muvee.style","msty"],
["en-us|MXML","application/xv+xml","mxml"],
["en-us|N-Gage Game Data","application/vnd.nokia.n-gage.data","ngdat"],
["en-us|N-Gage Game Installer","application/vnd.nokia.n-gage.symbian.install","n-gage"],
["en-us|Navigation Control file for XML (for ePub)","application/x-dtbncx+xml","ncx"],
["en-us|Network Common Data Form (NetCDF)","application/x-netcdf","nc"],
["en-us|neuroLanguage","application/vnd.neurolanguage.nlu","nlu"],
["en-us|New Moon Liftoff/DNA","application/vnd.dna","dna"],
["en-us|NobleNet Directory","application/vnd.noblenet-directory","nnd"],
["en-us|NobleNet Sealer","application/vnd.noblenet-sealer","nns"],
["en-us|NobleNet Web","application/vnd.noblenet-web","nnw"],
["en-us|Nokia Radio Application - Preset","application/vnd.nokia.radio-preset","rpst"],
["en-us|Nokia Radio Application - Preset","application/vnd.nokia.radio-presets","rpss"],
["en-us|Notation3","text/n3","n3"],
["en-us|Novadigm's RADIA and EDM products","application/vnd.novadigm.edm","edm"],
["en-us|Novadigm's RADIA and EDM products","application/vnd.novadigm.edx","edx"],
["en-us|Novadigm's RADIA and EDM products","application/vnd.novadigm.ext","ext"],
["en-us|NpGraphIt","application/vnd.flographit","gph"],
["en-us|Nuera ECELP 4800","audio/vnd.nuera.ecelp4800","ecelp4800"],
["en-us|Nuera ECELP 7470","audio/vnd.nuera.ecelp7470","ecelp7470"],
["en-us|Nuera ECELP 9600","audio/vnd.nuera.ecelp9600","ecelp9600"],
["en-us|Office Document Architecture","application/oda","oda"],
["en-us|Ogg","application/ogg","ogx"],
["en-us|Ogg Audio","audio/ogg","oga"],
["en-us|Ogg Video","video/ogg","ogv"],
["en-us|OMA Download Agents","application/vnd.oma.dd2+xml","dd2"],
["en-us|Open Document Text Web","application/vnd.oasis.opendocument.text-web","oth"],
["en-us|Open eBook Publication Structure","application/oebps-package+xml","opf"],
["en-us|Open Financial Exchange","application/vnd.intu.qbo","qbo"],
["en-us|Open Office Extension","application/vnd.openofficeorg.extension","oxt"],
["en-us|Open Score Format","application/vnd.yamaha.openscoreformat","osf"],
["en-us|Open Web Media Project - Audio","audio/webm","weba"],
["en-us|Open Web Media Project - Video","video/webm","webm"],
["en-us|OpenDocument Chart","application/vnd.oasis.opendocument.chart","odc"],
["en-us|OpenDocument Chart Template","application/vnd.oasis.opendocument.chart-template","otc"],
["en-us|OpenDocument Database","application/vnd.oasis.opendocument.database","odb"],
["en-us|OpenDocument Formula","application/vnd.oasis.opendocument.formula","odf"],
["en-us|OpenDocument Formula Template","application/vnd.oasis.opendocument.formula-template","odft"],
["en-us|OpenDocument Graphics","application/vnd.oasis.opendocument.graphics","odg"],
["en-us|OpenDocument Graphics Template","application/vnd.oasis.opendocument.graphics-template","otg"],
["en-us|OpenDocument Image","application/vnd.oasis.opendocument.image","odi"],
["en-us|OpenDocument Image Template","application/vnd.oasis.opendocument.image-template","oti"],
["en-us|OpenDocument Presentation","application/vnd.oasis.opendocument.presentation","odp"],
["en-us|OpenDocument Presentation Template","application/vnd.oasis.opendocument.presentation-template","otp"],
["en-us|OpenDocument Spreadsheet","application/vnd.oasis.opendocument.spreadsheet","ods"],
["en-us|OpenDocument Spreadsheet Template","application/vnd.oasis.opendocument.spreadsheet-template","ots"],
["en-us|OpenDocument Text","application/vnd.oasis.opendocument.text","odt"],
["en-us|OpenDocument Text Master","application/vnd.oasis.opendocument.text-master","odm"],
["en-us|OpenDocument Text Template","application/vnd.oasis.opendocument.text-template","ott"],
["en-us|OpenGL Textures (KTX)","image/ktx","ktx"],
["en-us|OpenOffice - Calc (Spreadsheet)","application/vnd.sun.xml.calc","sxc"],
["en-us|OpenOffice - Calc Template (Spreadsheet)","application/vnd.sun.xml.calc.template","stc"],
["en-us|OpenOffice - Draw (Graphics)","application/vnd.sun.xml.draw","sxd"],
["en-us|OpenOffice - Draw Template (Graphics)","application/vnd.sun.xml.draw.template","std"],
["en-us|OpenOffice - Impress (Presentation)","application/vnd.sun.xml.impress","sxi"],
["en-us|OpenOffice - Impress Template (Presentation)","application/vnd.sun.xml.impress.template","sti"],
["en-us|OpenOffice - Math (Formula)","application/vnd.sun.xml.math","sxm"],
["en-us|OpenOffice - Writer (Text - HTML)","application/vnd.sun.xml.writer","sxw"],
["en-us|OpenOffice - Writer (Text - HTML)","application/vnd.sun.xml.writer.global","sxg"],
["en-us|OpenOffice - Writer Template (Text - HTML)","application/vnd.sun.xml.writer.template","stw"],
["en-us|OpenType Font File","application/x-font-otf","otf"],
["en-us|OSFPVG","application/vnd.yamaha.openscoreformat.osfpvg+xml","osfpvg"],
["en-us|OSGi Deployment Package","application/vnd.osgi.dp","dp"],
["en-us|PalmOS Data","application/vnd.palm","pdb"],
["en-us|Pascal Source File","text/x-pascal","p"],
["en-us|PawaaFILE","application/vnd.pawaafile","paw"],
["en-us|PCL 6 Enhanced (Formely PCL XL)","application/vnd.hp-pclxl","pclxl"],
["en-us|Pcsel eFIF File","application/vnd.picsel","efif"],
["en-us|PCX Image","image/x-pcx","pcx"],
["en-us|Photoshop Document","image/vnd.adobe.photoshop","psd"],
["en-us|PICSRules","application/pics-rules","prf"],
["en-us|PICT Image","image/x-pict","pic"],
["en-us|pIRCh","application/x-chat","chat"],
["en-us|PKCS #10 - Certification Request Standard","application/pkcs10","p10"],
["en-us|PKCS #12 - Personal Information Exchange Syntax Standard","application/x-pkcs12","p12"],
["en-us|PKCS #7 - Cryptographic Message Syntax Standard","application/pkcs7-mime","p7m"],
["en-us|PKCS #7 - Cryptographic Message Syntax Standard","application/pkcs7-signature","p7s"],
["en-us|PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)","application/x-pkcs7-certreqresp","p7r"],
["en-us|PKCS #7 - Cryptographic Message Syntax Standard (Certificates)","application/x-pkcs7-certificates","p7b"],
["en-us|PKCS #8 - Private-Key Information Syntax Standard","application/pkcs8","p8"],
["en-us|PocketLearn Viewers","application/vnd.pocketlearn","plf"],
["en-us|Portable Anymap Image","image/x-portable-anymap","pnm"],
["en-us|Portable Bitmap Format","image/x-portable-bitmap","pbm"],
["en-us|Portable Compiled Format","application/x-font-pcf","pcf"],
["en-us|Portable Font Resource","application/font-tdpfr","pfr"],
["en-us|Portable Game Notation (Chess Games)","application/x-chess-pgn","pgn"],
["en-us|Portable Graymap Format","image/x-portable-graymap","pgm"],
["en-us|Portable Network Graphics (PNG)","image/png","png"],
["en-us|Portable Pixmap Format","image/x-portable-pixmap","ppm"],
["en-us|Portable Symmetric Key Container","application/pskc+xml","pskcxml"],
["en-us|PosML","application/vnd.ctc-posml","pml"],
["en-us|PostScript","application/postscript","ai"],
["en-us|PostScript Fonts","application/x-font-type1","pfa"],
["en-us|PowerBuilder","application/vnd.powerbuilder6","pbd"],
["en-us|Pretty Good Privacy","application/pgp-encrypted",""],
["en-us|Pretty Good Privacy - Signature","application/pgp-signature","pgp"],
["en-us|Preview Systems ZipLock/VBox","application/vnd.previewsystems.box","box"],
["en-us|Princeton Video Image","application/vnd.pvi.ptid1","ptid"],
["en-us|Pronunciation Lexicon Specification","application/pls+xml","pls"],
["en-us|Proprietary P&G Standard Reporting System","application/vnd.pg.format","str"],
["en-us|Proprietary P&G Standard Reporting System","application/vnd.pg.osasli","ei6"],
["en-us|PRS Lines Tag","text/prs.lines.tag","dsc"],
["en-us|PSF Fonts","application/x-font-linux-psf","psf"],
["en-us|PubliShare Objects","application/vnd.publishare-delta-tree","qps"],
["en-us|Qualcomm's Plaza Mobile Internet","application/vnd.pmi.widget","wg"],
["en-us|QuarkXpress","application/vnd.quark.quarkxpress","qxd"],
["en-us|QUASS Stream Player","application/vnd.epson.esf","esf"],
["en-us|QUASS Stream Player","application/vnd.epson.msf","msf"],
["en-us|QUASS Stream Player","application/vnd.epson.ssf","ssf"],
["en-us|QuickAnime Player","application/vnd.epson.quickanime","qam"],
["en-us|Quicken","application/vnd.intu.qfx","qfx"],
["en-us|Quicktime Video","video/quicktime","mov"],
["en-us|RAR Archive","application/x-rar-compressed","rar"],
["en-us|Real Audio Sound","audio/x-pn-realaudio","ram"],
["en-us|Real Audio Sound","audio/x-pn-realaudio-plugin","rmp"],
["en-us|Really Simple Discovery","application/rsd+xml","rsd"],
["en-us|RealMedia","application/vnd.rn-realmedia","rm"],
["en-us|RealVNC","application/vnd.realvnc.bed","bed"],
["en-us|Recordare Applications","application/vnd.recordare.musicxml","mxl"],
["en-us|Recordare Applications","application/vnd.recordare.musicxml+xml","musicxml"],
["en-us|Relax NG Compact Syntax","application/relax-ng-compact-syntax","rnc"],
["en-us|RemoteDocs R-Viewer","application/vnd.data-vision.rdz","rdz"],
["en-us|Resource Description Framework","application/rdf+xml","rdf"],
["en-us|RetroPlatform Player","application/vnd.cloanto.rp9","rp9"],
["en-us|RhymBox","application/vnd.jisp","jisp"],
["en-us|Rich Text Format","application/rtf","rtf"],
["en-us|Rich Text Format (RTF)","text/richtext","rtx"],
["en-us|ROUTE 66 Location Based Services","application/vnd.route66.link66+xml","link66"],
["en-us|RSS - Really Simple Syndication","application/rss+xml","rss, .xml"],
["en-us|S Hexdump Format","application/shf+xml","shf"],
["en-us|SailingTracker","application/vnd.sailingtracker.track","st"],
["en-us|Scalable Vector Graphics (SVG)","image/svg+xml","svg"],
["en-us|ScheduleUs","application/vnd.sus-calendar","sus"],
["en-us|Search/Retrieve via URL Response Format","application/sru+xml","sru"],
["en-us|Secure Electronic Transaction - Payment","application/set-payment-initiation","setpay"],
["en-us|Secure Electronic Transaction - Registration","application/set-registration-initiation","setreg"],
["en-us|Secured eMail","application/vnd.sema","sema"],
["en-us|Secured eMail","application/vnd.semd","semd"],
["en-us|Secured eMail","application/vnd.semf","semf"],
["en-us|SeeMail","application/vnd.seemail","see"],
["en-us|Server Normal Format","application/x-font-snf","snf"],
["en-us|Server-Based Certificate Validation Protocol - Validation Policies - Request","application/scvp-vp-request","spq"],
["en-us|Server-Based Certificate Validation Protocol - Validation Policies - Response","application/scvp-vp-response","spp"],
["en-us|Server-Based Certificate Validation Protocol - Validation Request","application/scvp-cv-request","scq"],
["en-us|Server-Based Certificate Validation Protocol - Validation Response","application/scvp-cv-response","scs"],
["en-us|Session Description Protocol","application/sdp","sdp"],
["en-us|Setext","text/x-setext","etx"],
["en-us|SGI Movie","video/x-sgi-movie","movie"],
["en-us|Shana Informed Filler","application/vnd.shana.informed.formdata","ifm"],
["en-us|Shana Informed Filler","application/vnd.shana.informed.formtemplate","itp"],
["en-us|Shana Informed Filler","application/vnd.shana.informed.interchange","iif"],
["en-us|Shana Informed Filler","application/vnd.shana.informed.package","ipk"],
["en-us|Sharing Transaction Fraud Data","application/thraud+xml","tfi"],
["en-us|Shell Archive","application/x-shar","shar"],
["en-us|Silicon Graphics RGB Bitmap","image/x-rgb","rgb"],
["en-us|SimpleAnimeLite Player","application/vnd.epson.salt","slt"],
["en-us|Simply Accounting","application/vnd.accpac.simply.aso","aso"],
["en-us|Simply Accounting - Data Import","application/vnd.accpac.simply.imp","imp"],
["en-us|SimTech MindMapper","application/vnd.simtech-mindmapper","twd"],
["en-us|Sixth Floor Media - CommonSpace","application/vnd.commonspace","csp"],
["en-us|SMAF Audio","application/vnd.yamaha.smaf-audio","saf"],
["en-us|SMAF File","application/vnd.smaf","mmf"],
["en-us|SMAF Phrase","application/vnd.yamaha.smaf-phrase","spf"],
["en-us|SMART Technologies Apps","application/vnd.smart.teacher","teacher"],
["en-us|SourceView Document","application/vnd.svd","svd"],
["en-us|SPARQL - Query","application/sparql-query","rq"],
["en-us|SPARQL - Results","application/sparql-results+xml","srx"],
["en-us|Speech Recognition Grammar Specification","application/srgs","gram"],
["en-us|Speech Recognition Grammar Specification - XML","application/srgs+xml","grxml"],
["en-us|Speech Synthesis Markup Language","application/ssml+xml","ssml"],
["en-us|SSEYO Koan Play File","application/vnd.koan","skp"],
["en-us|Standard Generalized Markup Language (SGML)","text/sgml","sgml"],
["en-us|StarOffice - Calc","application/vnd.stardivision.calc","sdc"],
["en-us|StarOffice - Draw","application/vnd.stardivision.draw","sda"],
["en-us|StarOffice - Impress","application/vnd.stardivision.impress","sdd"],
["en-us|StarOffice - Math","application/vnd.stardivision.math","smf"],
["en-us|StarOffice - Writer","application/vnd.stardivision.writer","sdw"],
["en-us|StarOffice - Writer (Global)","application/vnd.stardivision.writer-global","sgl"],
["en-us|StepMania","application/vnd.stepmania.stepchart","sm"],
["en-us|Stuffit Archive","application/x-stuffit","sit"],
["en-us|Stuffit Archive","application/x-stuffitx","sitx"],
["en-us|SudokuMagic","application/vnd.solent.sdkm+xml","sdkm"],
["en-us|Sugar Linux Application Bundle","application/vnd.olpc-sugar","xo"],
["en-us|Sun Audio - Au file format","audio/basic","au"],
["en-us|SundaHus WQ","application/vnd.wqd","wqd"],
["en-us|Symbian Install Package","application/vnd.symbian.install","sis"],
["en-us|Synchronized Multimedia Integration Language","application/smil+xml","smi"],
["en-us|SyncML","application/vnd.syncml+xml","xsm"],
["en-us|SyncML - Device Management","application/vnd.syncml.dm+wbxml","bdm"],
["en-us|SyncML - Device Management","application/vnd.syncml.dm+xml","xdm"],
["en-us|System V Release 4 CPIO Archive","application/x-sv4cpio","sv4cpio"],
["en-us|System V Release 4 CPIO Checksum Data","application/x-sv4crc","sv4crc"],
["en-us|Systems Biology Markup Language","application/sbml+xml","sbml"],
["en-us|Tab Seperated Values","text/tab-separated-values","tsv"],
["en-us|Tagged Image File Format","image/tiff","tiff"],
["en-us|Tao Intent","application/vnd.tao.intent-module-archive","tao"],
["en-us|Tar File (Tape Archive)","application/x-tar","tar"],
["en-us|Tcl Script","application/x-tcl","tcl"],
["en-us|TeX","application/x-tex","tex"],
["en-us|TeX Font Metric","application/x-tex-tfm","tfm"],
["en-us|Text Encoding and Interchange","application/tei+xml","tei"],
["en-us|Text File","text/plain","txt"],
["en-us|TIBCO Spotfire","application/vnd.spotfire.dxp","dxp"],
["en-us|TIBCO Spotfire","application/vnd.spotfire.sfs","sfs"],
["en-us|Time Stamped Data Envelope","application/timestamped-data","tsd"],
["en-us|TRI Systems Config","application/vnd.trid.tpt","tpt"],
["en-us|Triscape Map Explorer","application/vnd.triscape.mxs","mxs"],
["en-us|troff","text/troff","t"],
["en-us|True BASIC","application/vnd.trueapp","tra"],
["en-us|TrueType Font","application/x-font-ttf","ttf"],
["en-us|Turtle (Terse RDF Triple Language)","text/turtle","ttl"],
["en-us|UMAJIN","application/vnd.umajin","umj"],
["en-us|Unique Object Markup Language","application/vnd.uoml+xml","uoml"],
["en-us|Unity 3d","application/vnd.unity","unityweb"],
["en-us|Universal Forms Description Language","application/vnd.ufdl","ufd"],
["en-us|URI Resolution Services","text/uri-list","uri"],
["en-us|User Interface Quartz - Theme (Symbian)","application/vnd.uiq.theme","utz"],
["en-us|Ustar (Uniform Standard Tape Archive)","application/x-ustar","ustar"],
["en-us|UUEncode","text/x-uuencode","uu"],
["en-us|vCalendar","text/x-vcalendar","vcs"],
["en-us|vCard","text/x-vcard","vcf"],
["en-us|Video CD","application/x-cdlink","vcd"],
["en-us|Viewport+","application/vnd.vsf","vsf"],
["en-us|Virtual Reality Modeling Language","model/vrml","wrl"],
["en-us|VirtualCatalog","application/vnd.vcx","vcx"],
["en-us|Virtue MTS","model/vnd.mts","mts"],
["en-us|Virtue VTU","model/vnd.vtu","vtu"],
["en-us|Visionary","application/vnd.visionary","vis"],
["en-us|Vivo","video/vnd.vivo","viv"],
["en-us|Voice Browser Call Control","application/ccxml+xml,","ccxml"],
["en-us|VoiceXML","application/voicexml+xml","vxml"],
["en-us|WAIS Source","application/x-wais-source","src"],
["en-us|WAP Binary XML (WBXML)","application/vnd.wap.wbxml","wbxml"],
["en-us|WAP Bitamp (WBMP)","image/vnd.wap.wbmp","wbmp"],
["en-us|Waveform Audio File Format (WAV)","audio/x-wav","wav"],
["en-us|Web Distributed Authoring and Versioning","application/davmount+xml","davmount"],
["en-us|Web Open Font Format","application/x-font-woff","woff"],
["en-us|Web Services Policy","application/wspolicy+xml","wspolicy"],
["en-us|WebP Image","image/webp","webp"],
["en-us|WebTurbo","application/vnd.webturbo","wtb"],
["en-us|Widget Packaging and XML Configuration","application/widget","wgt"],
["en-us|WinHelp","application/winhlp","hlp"],
["en-us|Wireless Markup Language (WML)","text/vnd.wap.wml","wml"],
["en-us|Wireless Markup Language Script (WMLScript)","text/vnd.wap.wmlscript","wmls"],
["en-us|WMLScript","application/vnd.wap.wmlscriptc","wmlsc"],
["en-us|Wordperfect","application/vnd.wordperfect","wpd"],
["en-us|Worldtalk","application/vnd.wt.stf","stf"],
["en-us|WSDL - Web Services Description Language","application/wsdl+xml","wsdl"],
["en-us|X BitMap","image/x-xbitmap","xbm"],
["en-us|X PixMap","image/x-xpixmap","xpm"],
["en-us|X Window Dump","image/x-xwindowdump","xwd"],
["en-us|X.509 Certificate","application/x-x509-ca-cert","der"],
["en-us|Xfig","application/x-xfig","fig"],
["en-us|XHTML - The Extensible HyperText Markup Language","application/xhtml+xml","xhtml"],
["en-us|XML - Extensible Markup Language","application/xml","xml"],
["en-us|XML Configuration Access Protocol - XCAP Diff","application/xcap-diff+xml","xdf"],
["en-us|XML Encryption Syntax and Processing","application/xenc+xml","xenc"],
["en-us|XML Patch Framework","application/patch-ops-error+xml","xer"],
["en-us|XML Resource Lists","application/resource-lists+xml","rl"],
["en-us|XML Resource Lists","application/rls-services+xml","rs"],
["en-us|XML Resource Lists Diff","application/resource-lists-diff+xml","rld"],
["en-us|XML Transformations","application/xslt+xml","xslt"],
["en-us|XML-Binary Optimized Packaging","application/xop+xml","xop"],
["en-us|XPInstall - Mozilla","application/x-xpinstall","xpi"],
["en-us|XSPF - XML Shareable Playlist Format","application/xspf+xml","xspf"],
["en-us|XUL - XML User Interface Language","application/vnd.mozilla.xul+xml","xul"],
["en-us|XYZ File Format","chemical/x-xyz","xyz"],
["en-us|YANG Data Modeling Language","application/yang","yang"],
["en-us|YIN (YANG - XML)","application/yin+xml","yin"],
["en-us|Z.U.L. Geometry","application/vnd.zul","zir"],
["en-us|Zip Archive","application/zip","zip"],
["en-us|ZVUE Media Manager","application/vnd.handheld-entertainment+xml","zmm"],
["en-us|Zzazz Deck","application/vnd.zzazz.deck+xml","zaz"]]/*END_MIME_LIST*/;

sl.mimeInfo = function(mime) {
	for (var i = 0; i < sl.mimeList.length; i++) {
		if (sl.mimeList[i][1] == mime) return {
			"name":sl.mimeList[i][0],
			"type":sl.mimeList[i][1],
			"extension":sl.mimeList[i][2]
		};
	}
	return null;
};

sl.mimeName = function(mime) {
	var info;
	if (info = sl.mimeInfo(mime)) {
		return info.name;
	}
	return mime.split("/").pop();
};
